#!/bin/env bash

xrdb -merge "$XDG_CONFIG_HOME/Xresources" || true

~/.local/bin/screenlayout.sh || echo "screenlayout failed"

setxkbmap -layout us,ara -variant ,digits -option grp:win_space_toggle -option ctrl:nocaps
xset r rate 230 35 &

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
fi

exec i3
