#!/usr/bin/env bash

# Get default microphone info
status=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ 2>/dev/null)

# No microphone found
if [[ -z "$status" ]]; then
    echo " "
    echo " "
    echo "#928374"
    exit 0
fi

# Check mute state
if [[ "$status" == *"[MUTED]"* ]]; then
    echo " "
    echo " "
    echo "#fb4934"
else
    echo ""
    echo ""
    echo "#b8bb26"
fi
