#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O HDMI-A-0 DisplayPort-0
bspc monitor HDMI-A-0 -d 1 2 3 4 5
bspc monitor DisplayPort-0 -d 6 7 8 9 10

# Polybar
$HOME/.config/polybar/launch.sh

bspc config border_width        2
bspc config window_gap          10
bspc config top_padding         5
bspc config right_padding       5
bspc config bottom_padding      5
bspc config left_padding        5

bspc config split_ratio              0.5
bspc config automatic_scheme         longest_side
bspc config initial_polarity         second_child
bspc config borderless_monocle       true
bspc config gapless_monocle          true
bspc config focus_follows_pointer    true

bspc rule -a Spotify desktop='^5' state=tiling follow=off
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
