;;; modules.el --- Module toggle switchboard -*- lexical-binding: t; -*-

(require 'mod-essential-packages)
(require 'mod-navigation)
;; (require 'mod-evil)
;; (require 'mod-completion-builtin)
(require 'mod-dired)
(require 'mod-completion)
(require 'mod-consult)
(require 'mod-programming)
(require 'mod-treesitter)
(require 'mod-compile)
(require 'mod-project)
(require 'mod-sql)
(require 'mod-web)
(require 'mod-git)
;; (require 'mod-eglot)
;; (require 'mod-dape)
(require 'mod-lsp)
;; (require 'mod-java)
(require 'mod-dap)
(require 'mod-org)
(require 'mod-literate-programming)
(require 'mod-olivetti)
(require 'mod-vterm)
(require 'mod-eww)
(require 'mod-pdf)

(provide 'modules)

;;; modules.el ends here
