#!/usr/bin/env bash

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
fi

xrdb -merge "$XDG_CONFIG_HOME/x11/Xresources" || true
~/.local/bin/screenlayout.sh &>/dev/null || true

exec dbus-launch --sh-syntax --exit-with-session i3 --shmlog-size 0
