;;; verdigris-theme.el --- Minimal dark theme (black bg, green + teal accents) -*- lexical-binding: t -*-

;; Author: Ziad
;; A minimal dark theme built on the same structure as gruvbox-theme.el.
;; Palette: true-black background, off-white foreground, with green and teal
;; as the two signature accent hues (each with a bright/dim variant).
;; One muted red is kept, reserved only for genuine error/danger/destructive
;; states (compile errors, failed searches, deleted diff lines, "rm -rf"-tier
;; git actions, sudo). Everything else in the theme is grayscale + green/teal.
;; No palette switching, no gm/config menu, no light variant.

;;;###autoload
(deftheme verdigris
  "Verdigris: a black-background theme with green and teal as its signature accents.")

(let* (
       ;; Backgrounds
       (bg0 "#181616")
       (bg0-soft "#222020")
       (bg1 "#2a2828")
       (bg2 "#343232")
       (bg3 "#3e3c3c")
       (bg4 "#4e4c4c")
       ;; Foregrounds
       (fg-1 "#ffffff")
       (fg0 "#e9e9e9")
       (fg1 "#d2d2d2")
       (fg2 "#bbbbbb")
       (fg3 "#a4a4a4")
       (fg4 "#8d8d8d")
       (gray "#707070")
       ;; Signature accents -- these three hues ARE the theme
       (green "#a7b26c")
       (green-bright "#c0cb80")
       (green-dim "#858e5c")
       (teal "#659f94")
       (teal-bright "#81b8ad")
       (teal-dim "#537d76")
       ;; Minimal alert -- reserved for genuine error/danger/destructive states only
       (red "#a1453d")
       ;; Faded backgrounds (diffs / search highlights)
       (bg-red "#332019")
       (bg-green "#262d1c")
       (bg-teal "#1e332f")
       ;; Mode-line / powerline
       (bg-statusline1 "#2c2a2a")
       (bg-statusline2 "#232121")
       (bg-statusline3 "#363434")
       (bg-statusline4 "#413f3f"))

  (custom-theme-set-faces
   'verdigris
   `(default ((t (:background ,bg0 :foreground ,fg0))))
   `(bold    ((t (:foreground ,teal-bright :weight bold))))
   `(cursor ((t (:background ,fg0))))
   `(fringe ((t (:background ,bg0 :foreground ,gray))))
   `(hl-line ((t (:background ,bg1))))
   `(region ((t (:background ,bg-teal))))
   `(secondary-selection ((t (:background ,bg2))))
   `(vertical-border ((t (:foreground ,bg2))))
   `(fill-column-indicator ((t (:background ,bg1 :foreground ,bg1))))
   `(minibuffer-prompt ((t (:foreground ,teal :weight semi-bold))))
   `(link ((t (:foreground ,teal-bright :underline t))))
   `(link-visited ((t (:foreground ,teal-dim :underline t))))
   `(highlight ((t (:background ,bg-teal))))
   `(lazy-highlight ((t (:background ,bg-green :foreground ,fg0))))
   `(isearch ((t (:background ,bg-teal :foreground ,fg-1 :weight bold))))
   `(isearch-fail ((t (:background ,bg-red :foreground ,red))))
   `(match ((t (:background ,bg-green :foreground ,fg0))))
   `(show-paren-match ((t (:background ,bg-teal :foreground ,green-bright :weight bold))))
   `(show-paren-mismatch ((t (:background ,bg-red :foreground ,red :weight bold))))
   `(shadow ((t (:foreground ,gray))))
   `(error ((t (:foreground ,red :weight bold))))
   `(warning ((t (:foreground ,teal-bright :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))
   `(button ((t (:foreground ,teal-bright :underline t))))
   `(header-line ((t (:background ,bg2 :foreground ,fg0))))
   `(header-line-highlight ((t (:background ,bg3 :foreground ,fg0))))
   `(help-key-binding ((t (:foreground ,teal :background ,bg2 :box (:line-width 1 :color ,bg3)))))
   `(homoglyph ((t (:foreground ,teal))))
   `(nobreak-hyphen ((t (:foreground ,red))))
   `(escape-glyph ((t (:foreground ,teal))))
   `(completions-common-part ((t (:foreground ,teal :weight bold))))
   `(completions-first-difference ((t (:foreground ,green-bright :weight bold))))
   `(completions-annotations ((t (:foreground ,bg4 :slant italic))))
   `(widget-field ((t (:background ,bg2 :foreground ,fg0))))
   `(widget-button ((t (:foreground ,teal-bright :weight bold))))
   `(tooltip ((t (:background ,bg3 :foreground ,fg-1))))
   `(line-number ((t (:background ,bg0 :foreground ,bg4 :inherit fixed-pitch :height 1.0))))
   `(line-number-current-line ((t (:background ,bg0 :foreground ,green-bright :weight bold :inherit fixed-pitch :height 1.0))))
   `(mode-line ((t (:background ,bg-statusline1 :foreground ,fg2 :box (:line-width 1 :color ,bg2)))))
   `(mode-line-inactive ((t (:background ,bg-statusline2 :foreground ,gray :box (:line-width 1 :color ,bg2)))))
   `(mode-line-buffer-id ((t (:foreground ,fg1 :weight semi-bold))))
   `(mode-line-emphasis ((t (:foreground ,fg1 :weight semi-bold))))
   `(mode-line-highlight ((t (:foreground ,teal-bright))))
   `(tab-bar ((t (:background ,bg0 :foreground ,gray))))
   `(tab-bar-tab ((t (:background ,bg2 :foreground ,fg0 :weight semi-bold :box (:line-width 1 :color ,bg3)))))
   `(tab-bar-tab-inactive ((t (:background ,bg0 :foreground ,gray :box (:line-width 1 :color ,bg2)))))
   `(tab-line ((t (:background ,bg0 :foreground ,gray))))
   `(tab-line-tab ((t (:background ,bg2 :foreground ,fg0 :weight semi-bold :box (:line-width 1 :color ,bg3)))))
   `(tab-line-tab-current ((t (:background ,bg2 :foreground ,green-bright :weight semi-bold :box (:line-width 1 :color ,bg3)))))
   `(tab-line-tab-inactive ((t (:background ,bg0 :foreground ,gray :box (:line-width 1 :color ,bg2)))))
   `(tab-line-tab-modified ((t (:foreground ,teal-bright))))
   `(tab-line-highlight ((t (:background ,bg3 :foreground ,fg0))))
   `(tab-line-close-highlight ((t (:foreground ,red))))
   `(whitespace-space ((t (:foreground ,bg3 :background unspecified))))
   `(whitespace-hspace ((t (:foreground ,bg3 :background unspecified))))
   `(whitespace-tab ((t (:foreground ,bg3 :background unspecified))))
   `(whitespace-newline ((t (:foreground ,bg3 :background unspecified))))
   `(whitespace-trailing ((t (:foreground ,red :background ,bg-red))))
   `(whitespace-line ((t (:foreground ,red :background ,bg-red))))
   `(whitespace-space-before-tab ((t (:foreground ,green-bright :background unspecified))))
   `(whitespace-space-after-tab ((t (:foreground ,green-bright :background unspecified))))
   `(whitespace-indentation ((t (:foreground ,bg4 :background unspecified))))
   `(whitespace-empty ((t (:background ,bg-red))))
   `(whitespace-missing-newline-at-eof ((t (:foreground ,green-bright))))
   `(font-lock-doc-markup-face ((t (:inherit font-lock-keyword-face))))
   `(font-lock-keyword-face ((t (:foreground ,teal-bright :weight regular))))
   `(font-lock-type-face ((t (:foreground ,green-bright :weight regular))))
   `(font-lock-builtin-face ((t (:foreground ,green-dim :weight regular))))
   `(font-lock-function-name-face ((t (:foreground ,teal :weight normal))))
   `(font-lock-function-call-face ((t (:foreground ,fg0 :weight normal))))
   `(font-lock-variable-name-face ((t (:foreground ,fg0 :weight normal))))
   `(font-lock-variable-use-face ((t (:foreground ,fg0 :weight normal))))
   `(font-lock-constant-face ((t (:foreground ,teal-dim))))
   `(font-lock-string-face ((t (:foreground ,green :slant italic))))
   `(font-lock-doc-face ((t (:foreground ,gray :slant italic))))
   `(font-lock-comment-face ((t (:foreground ,gray :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,bg4 :slant italic))))
   `(font-lock-preprocessor-face ((t (:foreground ,teal :weight semi-bold))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(font-lock-escape-face ((t (:foreground ,green-bright))))
   `(font-lock-operator-face ((t (:foreground ,fg0 :weight normal))))
   `(font-lock-bracket-face ((t (:foreground ,green-bright :weight normal))))
   `(font-lock-delimiter-face ((t (:foreground ,fg3))))
   `(font-lock-punctuation-face ((t (:foreground ,teal :weight semi-bold))))
   `(font-lock-property-name-face ((t (:foreground ,teal-bright :weight normal))))
   `(font-lock-property-use-face ((t (:foreground ,teal-bright :weight normal))))
   `(font-lock-number-face ((t (:foreground ,teal-dim))))
   `(font-lock-negation-char-face ((t (:foreground ,green-bright))))
   `(treesit-fold-replacement-face ((t (:foreground ,gray :box (:line-width 1 :color ,bg3)))))
   `(treesit-fold-fringe-face ((t (:foreground ,gray))))
   `(font-lock-misc-punctuation-face ((t (:foreground ,teal))))
   `(smerge-lower ((t (:background ,bg-green))))
   `(smerge-upper ((t (:background ,bg-red))))
   `(smerge-base ((t (:background ,bg-teal))))
   `(smerge-markers ((t (:background ,bg2 :weight bold))))
   `(diff-added ((t (:background ,bg-green :foreground ,green))))
   `(diff-removed ((t (:background ,bg-red :foreground ,red))))
   `(diff-changed ((t (:background ,bg-teal :foreground ,teal-bright))))
   `(diff-header ((t (:background ,bg2 :foreground ,fg0 :weight bold))))
   `(diff-file-header ((t (:background ,bg2 :foreground ,fg0 :weight bold))))
   `(diff-hunk-header ((t (:background ,bg2 :foreground ,green-bright))))
   `(diff-hl-insert ((t (:foreground ,green :background unspecified))))
   `(diff-hl-delete ((t (:foreground ,red :background unspecified))))
   `(diff-hl-change ((t (:foreground ,teal-bright :background unspecified))))
   `(diff-hl-margin-insert ((t (:foreground ,green :background unspecified))))
   `(diff-hl-margin-delete ((t (:foreground ,red :background unspecified))))
   `(diff-hl-margin-change ((t (:foreground ,teal-bright :background unspecified))))
   `(diff-hl-reverted-hunk-highlight ((t (:background ,bg-green))))
   `(magit-section-heading ((t (:foreground ,teal :weight semi-bold :extend t))))
   `(magit-section-heading-selection ((t (:foreground ,teal-bright :weight semi-bold :extend t))))
   `(magit-section-secondary-heading ((t (:foreground ,teal-dim :weight semi-bold :extend t))))
   `(magit-section-highlight ((t (:background ,bg1 :extend t))))
   `(magit-filename ((t (:foreground ,teal-dim :weight regular))))
   `(magit-hash ((t (:foreground ,bg4))))
   `(magit-tag ((t (:foreground ,green-bright))))
   `(magit-dimmed ((t (:foreground ,bg4))))
   `(magit-diff-file-heading ((t (:foreground ,fg0 :weight semi-bold :extend t))))
   `(magit-diff-file-heading-highlight ((t (:background ,bg1 :weight semi-bold :extend t))))
   `(magit-diff-file-heading-selection ((t (:foreground ,teal-dim :background ,bg-teal :weight bold :extend t))))
   `(magit-diff-hunk-heading ((t (:background ,bg1 :foreground ,gray :extend t))))
   `(magit-diff-hunk-heading-highlight ((t (:background ,bg2 :foreground ,fg0 :weight semi-bold :extend t))))
   `(magit-diff-lines-heading ((t (:background ,green-bright :foreground ,bg0 :extend t))))
   `(magit-diff-context ((t (:foreground ,bg4 :background ,bg0 :extend t))))
   `(magit-diff-context-highlight ((t (:foreground ,fg0 :background ,bg0 :extend t))))
   `(magit-diff-added ((t (:foreground ,green :extend t))))
   `(magit-diff-added-highlight ((t (:background ,bg-green :foreground ,green :weight semi-bold :extend t))))
   `(magit-diff-removed ((t (:foreground ,red :extend t))))
   `(magit-diff-removed-highlight ((t (:background ,bg-red :foreground ,red :weight semi-bold :extend t))))
   `(magit-diff-base ((t (:background ,bg-teal :foreground ,teal-bright :extend t))))
   `(magit-diff-base-highlight ((t (:background ,bg-teal :foreground ,teal-bright :weight semi-bold :extend t))))
   `(magit-diffstat-added ((t (:foreground ,green))))
   `(magit-diffstat-removed ((t (:foreground ,red))))
   `(magit-branch-current ((t (:foreground ,green-bright :weight semi-bold))))
   `(magit-branch-local ((t (:foreground ,green-bright :weight semi-bold))))
   `(magit-branch-remote ((t (:foreground ,teal :weight semi-bold))))
   `(magit-log-author ((t (:foreground ,teal-dim))))
   `(magit-log-date ((t (:foreground ,teal))))
   `(magit-log-graph ((t (:foreground ,bg4))))
   `(magit-blame-heading ((t (:foreground ,teal-bright :background ,bg2 :extend t))))
   `(magit-blame-hash ((t (:foreground ,teal))))
   `(magit-blame-date ((t (:foreground ,teal-dim))))
   `(magit-bisect-bad ((t (:foreground ,red))))
   `(magit-bisect-good ((t (:foreground ,green))))
   `(magit-bisect-skip ((t (:foreground ,green-bright))))
   `(magit-cherry-equivalent ((t (:foreground ,teal-dim))))
   `(magit-cherry-unmatched ((t (:foreground ,teal))))
   `(magit-reflog-amend ((t (:foreground ,teal-dim))))
   `(magit-reflog-checkout ((t (:foreground ,teal-bright))))
   `(magit-reflog-cherry-pick ((t (:foreground ,green))))
   `(magit-reflog-commit ((t (:foreground ,green))))
   `(magit-reflog-merge ((t (:foreground ,green))))
   `(magit-reflog-other ((t (:foreground ,teal))))
   `(magit-reflog-rebase ((t (:foreground ,teal-dim))))
   `(magit-reflog-remote ((t (:foreground ,teal))))
   `(magit-reflog-reset ((t (:foreground ,red :weight semi-bold))))
   `(magit-sequence-drop ((t (:foreground ,red))))
   `(magit-sequence-head ((t (:foreground ,teal-bright))))
   `(magit-sequence-part ((t (:foreground ,green-bright))))
   `(magit-sequence-stop ((t (:foreground ,green))))
   `(magit-signature-good ((t (:foreground ,green))))
   `(magit-signature-bad ((t (:foreground ,red :weight semi-bold))))
   `(magit-signature-error ((t (:foreground ,red))))
   `(magit-signature-expired ((t (:foreground ,green-bright))))
   `(magit-signature-revoked ((t (:foreground ,teal-dim))))
   `(magit-signature-untrusted ((t (:foreground ,teal-bright))))
   `(magit-process-ok ((t (:foreground ,green :weight semi-bold))))
   `(magit-process-ng ((t (:foreground ,red :weight semi-bold))))
   `(git-commit-summary ((t (:foreground ,fg0 :weight semi-bold))))
   `(git-commit-overlong-summary ((t (:foreground ,red :weight semi-bold))))
   `(git-commit-nonempty-second-line ((t (:foreground ,red))))
   `(git-commit-keyword ((t (:foreground ,teal))))
   `(git-commit-pseudo-header ((t (:foreground ,gray))))
   `(git-commit-known-pseudo-header ((t (:foreground ,teal-bright :weight semi-bold))))
   `(git-commit-comment-branch-local ((t (:foreground ,green-bright))))
   `(git-commit-comment-branch-remote ((t (:foreground ,green))))
   `(git-commit-comment-heading ((t (:foreground ,teal :weight semi-bold))))
   `(git-commit-comment-file ((t (:foreground ,teal-dim))))
   `(git-commit-comment-action ((t (:foreground ,green-bright))))
   `(dired-directory ((t (:foreground ,teal-bright :weight semi-bold))))
   `(dired-symlink ((t (:foreground ,teal :slant italic))))
   `(dired-flagged ((t (:foreground ,red :weight semi-bold))))
   `(dired-marked ((t (:foreground ,green-bright :weight semi-bold))))
   `(dired-header ((t (:foreground ,green :weight semi-bold))))
   `(org-level-1 ((t (:inherit default :foreground ,teal-bright :weight bold))))
   `(org-level-2 ((t (:inherit default :foreground ,green-bright :weight bold))))
   `(org-level-3 ((t (:inherit default :foreground ,teal :weight semi-bold))))
   `(org-level-4 ((t (:inherit default :foreground ,green :weight semi-bold))))
   `(org-level-5 ((t (:inherit default :foreground ,teal-dim :weight semi-bold))))
   `(org-level-6 ((t (:inherit default :foreground ,green-dim :weight semi-bold))))
   `(org-level-7 ((t (:inherit default :foreground ,fg2 :weight semi-bold))))
   `(org-level-8 ((t (:inherit default :foreground ,fg3 :weight semi-bold))))
   `(org-document-info-keyword ((t (:foreground ,fg4 :inherit fixed-pitch))))
   `(org-document-title ((t (:foreground ,teal-bright :weight semi-bold))))
   `(org-document-info ((t (:foreground ,fg1))))
   `(org-meta-line ((t (:foreground ,green-dim :inherit fixed-pitch))))
   `(org-todo ((t (:foreground ,green-bright :weight bold))))
   `(org-done ((t (:foreground ,gray :weight bold))))
   `(org-headline-done ((t (:foreground ,gray :strike-through t))))
   `(org-priority ((t (:foreground ,teal-bright))))
   `(org-keyword ((t (:foreground ,green-bright :weight semi-bold))))
   `(org-tag ((t (:foreground ,bg4 :slant italic))))
   `(org-tag-group ((t (:foreground ,fg4 :slant italic))))
   `(org-special-keyword ((t (:foreground ,fg4 :inherit fixed-pitch))))
   `(org-property-value ((t (:foreground ,fg2 :inherit fixed-pitch))))
   `(org-block ((t (:background ,bg0-soft :extend t :inherit fixed-pitch :height 1.0))))
   `(org-block-begin-line ((t (:background ,bg0-soft :foreground ,bg4 :slant italic :extend t :inherit fixed-pitch :height 1.0))))
   `(org-block-end-line ((t (:background ,bg0-soft :foreground ,bg4 :slant italic :extend t :inherit fixed-pitch :height 1.0))))
   `(org-code ((t (:foreground ,teal-dim :background ,bg0-soft :inherit fixed-pitch :height 1.0))))
   `(org-verbatim ((t (:foreground ,teal-dim :background ,bg0-soft :inherit fixed-pitch :height 1.0))))
   `(org-link ((t (:foreground ,teal :inherit fixed-pitch :underline t))))
   `(org-footnote ((t (:foreground ,teal :underline t :slant italic))))
   `(org-table ((t (:foreground ,fg2 :inherit fixed-pitch :height 1.0))))
   `(org-formula ((t (:foreground ,green-bright :inherit fixed-pitch :height 1.0))))
   `(org-column ((t (:background ,bg0-soft))))
   `(org-column-title ((t (:background ,bg0-soft :weight bold :underline t))))
   `(org-date ((t (:foreground ,teal-dim :underline t :inherit fixed-pitch :height 1.0))))
   `(org-date-selected ((t (:foreground ,green-bright :weight bold))))
   `(org-scheduled ((t (:foreground ,fg2))))
   `(org-scheduled-today ((t (:foreground ,green :weight semi-bold))))
   `(org-scheduled-previously ((t (:foreground ,red))))
   `(org-upcoming-deadline ((t (:foreground ,green-bright))))
   `(org-warning ((t (:foreground ,red :weight bold))))
   `(org-agenda-date ((t (:foreground ,fg4))))
   `(org-agenda-date-today ((t (:foreground ,green-bright :weight bold))))
   `(org-agenda-date-weekend ((t (:foreground ,fg4 :slant italic))))
   `(org-agenda-structure ((t (:foreground ,teal-dim :weight bold))))
   `(org-agenda-done ((t (:foreground ,gray :strike-through t))))
   `(org-agenda-clocking ((t (:background ,bg-teal))))
   `(org-agenda-current-time ((t (:foreground ,green-bright :weight bold))))
   `(org-time-grid ((t (:foreground ,bg4))))
   `(org-drawer ((t (:foreground ,bg4 :inherit fixed-pitch))))
   `(org-ellipsis ((t (:foreground ,bg4))))
   `(org-hide ((t (:foreground ,bg0))))
   `(org-list-dt ((t (:foreground ,green-bright :weight semi-bold))))
   `(org-checkbox ((t (:foreground ,green-bright :weight bold :inherit fixed-pitch :height 1.0))))
   `(org-checkbox-statistics-todo ((t (:foreground ,green-bright :weight bold))))
   `(org-checkbox-statistics-done ((t (:foreground ,green :weight bold))))
   `(Man-overstrike ((t (:foreground ,fg0 :weight semi-bold))))
   `(Man-underline ((t (:foreground ,fg0 :underline t))))
   `(Man-reverse ((t (:foreground ,teal-bright :weight bold))))
   `(info-title-1 ((t (:foreground ,teal-bright :weight bold :height 1.2))))
   `(info-title-2 ((t (:foreground ,green-bright :weight bold :height 1.1))))
   `(info-title-3 ((t (:foreground ,green :weight semi-bold))))
   `(info-title-4 ((t (:foreground ,teal :weight semi-bold))))
   `(info-header-node ((t (:foreground ,teal :weight bold))))
   `(info-header-xref ((t (:foreground ,teal-bright :underline t))))
   `(info-node ((t (:foreground ,teal :weight bold :slant italic))))
   `(info-xref ((t (:foreground ,teal-bright :underline t))))
   `(info-xref-visited ((t (:foreground ,teal-dim :underline t))))
   `(info-menu-header ((t (:foreground ,green-bright :weight bold))))
   `(info-menu-star ((t (:foreground ,teal-bright))))
   `(info-index-match ((t (:background ,bg-green :foreground ,green))))
   `(ido-first-match ((t (:foreground ,green-bright :weight semi-bold))))
   `(ido-only-match ((t (:foreground ,green :weight semi-bold))))
   `(ido-subdir ((t (:foreground ,teal-bright :weight semi-bold))))
   `(ido-virtual ((t (:foreground ,gray :slant italic))))
   `(ido-indicator ((t (:foreground ,teal-bright :weight bold))))
   `(ido-incomplete-regexp ((t (:foreground ,red :weight bold))))
   `(vertico-current ((t (:background ,bg1 :foreground ,fg-1 :weight semi-bold))))
   `(orderless-match-face-0 ((t (:foreground ,green-bright :weight semi-bold))))
   `(orderless-match-face-1 ((t (:foreground ,teal :weight semi-bold))))
   `(orderless-match-face-2 ((t (:foreground ,teal-dim :weight semi-bold))))
   `(orderless-match-face-3 ((t (:foreground ,teal-bright :weight semi-bold))))
   `(marginalia-key ((t (:foreground ,green-bright))))
   `(marginalia-type ((t (:foreground ,teal-bright))))
   `(marginalia-char ((t (:foreground ,green-bright))))
   `(marginalia-date ((t (:foreground ,teal-dim))))
   `(marginalia-size ((t (:foreground ,gray))))
   `(marginalia-file-name ((t (:foreground ,fg3))))
   `(marginalia-file-priv-no ((t (:foreground ,bg4))))
   `(marginalia-documentation ((t (:foreground ,gray :slant italic))))
   `(corfu-default ((t (:background ,bg1 :foreground ,fg0))))
   `(corfu-current ((t (:background ,bg-teal :foreground ,fg-1 :weight semi-bold))))
   `(corfu-border ((t (:background ,bg3))))
   `(corfu-bar ((t (:background ,gray))))
   `(corfu-annotations ((t (:foreground ,gray))))
   `(company-tooltip ((t (:background ,bg1 :foreground ,fg0))))
   `(company-tooltip-common ((t (:foreground ,teal :weight semi-bold))))
   `(company-tooltip-selection ((t (:background ,bg-teal :foreground ,fg-1 :weight semi-bold))))
   `(company-tooltip-common-selection ((t (:foreground ,teal :weight bold))))
   `(company-tooltip-search ((t (:background ,bg-green :foreground ,green-bright :weight semi-bold))))
   `(company-tooltip-search-selection ((t (:background ,green-bright :foreground ,bg0 :weight bold))))
   `(company-tooltip-annotation ((t (:foreground ,gray))))
   `(company-tooltip-annotation-selection ((t (:foreground ,fg-1))))
   `(company-scrollbar-bg ((t (:background ,bg2))))
   `(company-scrollbar-fg ((t (:background ,fg4))))
   `(company-preview ((t (:foreground ,fg3))))
   `(company-preview-common ((t (:foreground ,teal :weight semi-bold))))
   `(company-preview-search ((t (:foreground ,green-bright))))
   `(company-echo-common ((t (:foreground ,teal :weight bold))))
   `(ivy-current-match ((t (:background ,bg2 :weight semi-bold :extend t))))
   `(ivy-minibuffer-match-face-1 ((t (:foreground ,gray :background nil))))
   `(ivy-minibuffer-match-face-2 ((t (:background nil :foreground ,green-bright :weight semi-bold))))
   `(ivy-minibuffer-match-face-3 ((t (:background nil :foreground ,teal :weight semi-bold))))
   `(ivy-minibuffer-match-face-4 ((t (:background nil :foreground ,teal-dim :weight semi-bold))))
   `(ivy-minibuffer-match-highlight ((t (:background nil :foreground ,green-bright :weight bold))))
   `(ivy-confirm-face ((t (:foreground ,green))))
   `(ivy-match-required-face ((t (:foreground ,red))))
   `(ivy-highlight-face ((t (:foreground ,teal :weight semi-bold))))
   `(ivy-separator ((t (:foreground ,bg3))))
   `(ivy-prompt-match ((t (:foreground ,teal-bright))))
   `(ivy-subdir ((t (:foreground ,teal-bright :weight semi-bold))))
   `(ivy-virtual ((t (:foreground ,gray :slant italic))))
   `(ivy-remote ((t (:foreground ,teal))))
   `(ivy-modified-buffer ((t (:foreground ,teal-bright))))
   `(ivy-modified-outside-buffer ((t (:foreground ,green-bright))))
   `(ivy-action ((t (:foreground ,teal-bright :weight semi-bold))))
   `(ivy-grep-info ((t (:foreground ,green))))
   `(ivy-grep-line-number ((t (:foreground ,teal-dim))))
   `(ivy-rich-doc-face ((t (:foreground ,gray :slant italic))))
   `(ivy-rich-path-face ((t (:foreground ,teal-bright))))
   `(ivy-rich-annotation-face ((t (:foreground ,gray))))
   `(ivy-rich-modifier-face ((t (:foreground ,teal-bright))))
   `(swiper-line-face ((t (:background ,bg2 :weight semi-bold :extend t))))
   `(swiper-match-face-1 ((t (:foreground ,gray :background nil))))
   `(swiper-match-face-2 ((t (:background nil :foreground ,green-bright :weight semi-bold))))
   `(swiper-match-face-3 ((t (:background nil :foreground ,teal :weight semi-bold))))
   `(swiper-match-face-4 ((t (:background nil :foreground ,teal-dim :weight semi-bold))))
   `(swiper-background-match-face-1 ((t (:foreground ,gray :background nil))))
   `(swiper-background-match-face-2 ((t (:background nil :foreground ,green-bright))))
   `(swiper-background-match-face-3 ((t (:background nil :foreground ,teal))))
   `(swiper-background-match-face-4 ((t (:background nil :foreground ,teal-dim))))
   `(swiper-isearch-match ((t (:background nil :foreground ,green-bright :weight semi-bold))))
   `(swiper-isearch-match-highlight ((t (:background nil :foreground ,fg-1 :weight bold))))
   `(vterm-color-default ((t (:foreground ,fg0 :background ,bg0))))
   `(vterm-color-black ((t (:foreground ,bg1 :background ,bg4))))
   `(vterm-color-red ((t (:foreground ,red :background ,red))))
   `(vterm-color-green ((t (:foreground ,green :background ,green))))
   `(vterm-color-yellow ((t (:foreground ,green-bright :background ,green-bright))))
   `(vterm-color-blue ((t (:foreground ,teal-bright :background ,teal-bright))))
   `(vterm-color-magenta ((t (:foreground ,teal-dim :background ,teal-dim))))
   `(vterm-color-cyan ((t (:foreground ,teal :background ,teal))))
   `(vterm-color-white ((t (:foreground ,fg0 :background ,fg3))))
   `(vterm-color-bright-black ((t (:foreground ,gray :background ,fg4))))
   `(vterm-color-bright-red ((t (:foreground ,red :background ,red))))
   `(vterm-color-bright-green ((t (:foreground ,green :background ,green))))
   `(vterm-color-bright-yellow ((t (:foreground ,green-bright :background ,green-bright))))
   `(vterm-color-bright-blue ((t (:foreground ,teal-bright :background ,teal-bright))))
   `(vterm-color-bright-magenta ((t (:foreground ,teal-dim :background ,teal-dim))))
   `(vterm-color-bright-cyan ((t (:foreground ,teal :background ,teal))))
   `(vterm-color-bright-white ((t (:foreground ,fg-1 :background ,fg-1))))
   `(vterm-color-underline ((t (:underline t))))
   `(vterm-color-inverse-video ((t (:foreground ,bg0 :background ,fg0))))
   `(eshell-prompt ((t (:foreground ,green :weight bold))))
   `(eshell-ls-directory ((t (:foreground ,teal-bright :weight semi-bold))))
   `(eshell-ls-symlink ((t (:foreground ,teal :slant italic))))
   `(eshell-ls-executable ((t (:foreground ,green :weight semi-bold))))
   `(eshell-ls-archive ((t (:foreground ,teal-dim :weight semi-bold))))
   `(eshell-ls-readonly ((t (:foreground ,teal-dim))))
   `(eshell-ls-unreadable ((t (:foreground ,bg4))))
   `(eshell-ls-special ((t (:foreground ,teal-dim :weight semi-bold))))
   `(eshell-ls-missing ((t (:foreground ,red :weight bold :underline t))))
   `(eshell-ls-product ((t (:foreground ,green-bright))))
   `(eshell-ls-clutter ((t (:foreground ,bg4))))
   `(eshell-ls-backup ((t (:foreground ,gray))))
   `(comint-highlight-prompt ((t (:foreground ,green :weight bold))))
   `(comint-highlight-input ((t (:foreground ,fg-1))))
   `(term ((t (:background ,bg0 :foreground ,fg0))))
   `(term-color-black ((t (:foreground ,bg1 :background ,bg4))))
   `(term-color-red ((t (:foreground ,red :background ,red))))
   `(term-color-green ((t (:foreground ,green :background ,green))))
   `(term-color-yellow ((t (:foreground ,green-bright :background ,green-bright))))
   `(term-color-blue ((t (:foreground ,teal-bright :background ,teal-bright))))
   `(term-color-magenta ((t (:foreground ,teal-dim :background ,teal-dim))))
   `(term-color-cyan ((t (:foreground ,teal :background ,teal))))
   `(term-color-white ((t (:foreground ,fg0 :background ,fg3))))
   `(term-color-bright-black ((t (:foreground ,gray :background ,fg4))))
   `(term-color-bright-red ((t (:foreground ,red :background ,red))))
   `(term-color-bright-green ((t (:foreground ,green :background ,green))))
   `(term-color-bright-yellow ((t (:foreground ,green-bright :background ,green-bright))))
   `(term-color-bright-blue ((t (:foreground ,teal-bright :background ,teal-bright))))
   `(term-color-bright-magenta ((t (:foreground ,teal-dim :background ,teal-dim))))
   `(term-color-bright-cyan ((t (:foreground ,teal :background ,teal))))
   `(term-color-bright-white ((t (:foreground ,fg-1 :background ,fg-1))))
   `(term-underline ((t (:underline t))))
   `(powerline-active0 ((t (:background ,bg-statusline1 :foreground ,fg1))))
   `(powerline-active1 ((t (:background ,bg-statusline3 :foreground ,fg1))))
   `(powerline-active2 ((t (:background ,bg-statusline4 :foreground ,fg2))))
   `(powerline-inactive0 ((t (:background ,bg-statusline2 :foreground ,gray))))
   `(powerline-inactive1 ((t (:background ,bg0-soft :foreground ,gray))))
   `(powerline-inactive2 ((t (:background ,bg-statusline3 :foreground ,bg4))))
   `(powerline-evil-normal-face ((t (:background ,teal :foreground ,bg0 :weight bold))))
   `(powerline-evil-insert-face ((t (:background ,green :foreground ,bg0 :weight bold))))
   `(powerline-evil-visual-face ((t (:background ,green-bright :foreground ,bg0 :weight bold))))
   `(powerline-evil-replace-face ((t (:background ,red :foreground ,bg0 :weight bold))))
   `(powerline-evil-operator-face ((t (:background ,green-dim :foreground ,bg0 :weight bold))))
   `(powerline-evil-motion-face ((t (:background ,teal-dim :foreground ,bg0 :weight bold))))
   `(powerline-evil-emacs-face ((t (:background ,teal-bright :foreground ,bg0 :weight bold))))
   `(sml/global ((t (:background ,bg-statusline1 :foreground ,fg2))))
   `(sml/modes ((t (:background ,bg-statusline1 :foreground ,fg2))))
   `(sml/minor-modes ((t (:background ,bg-statusline1 :foreground ,gray))))
   `(sml/filename ((t (:foreground ,green-bright :weight semi-bold))))
   `(sml/prefix ((t (:foreground ,teal-dim :weight semi-bold))))
   `(sml/folder ((t (:foreground ,gray))))
   `(sml/not-modified ((t (:foreground ,fg2))))
   `(sml/modified ((t (:foreground ,teal-bright :weight bold))))
   `(sml/outside-modified ((t (:foreground ,red :weight bold))))
   `(sml/read-only ((t (:foreground ,teal :weight semi-bold))))
   `(sml/remote ((t (:foreground ,teal-dim))))
   `(sml/sudo ((t (:foreground ,red :weight bold))))
   `(sml/line-number ((t (:foreground ,fg1 :weight semi-bold))))
   `(sml/col-number ((t (:foreground ,fg2))))
   `(sml/numbers-separator ((t (:foreground ,bg4))))
   `(sml/position-percentage ((t (:foreground ,gray))))
   `(sml/process ((t (:foreground ,teal-dim))))
   `(sml/time ((t (:foreground ,gray))))
   `(sml/client ((t (:foreground ,teal-dim))))
   `(sml/mule-info ((t (:foreground ,gray))))
   `(sml/charging ((t (:foreground ,green))))
   `(sml/discharging ((t (:foreground ,green-bright))))
   `(sml/projectile-replacement-face ((t (:foreground ,teal-dim :weight semi-bold))))
   `(eww-default-colors ((t (:background ,bg0 :foreground ,fg0))))
   `(shr-h1 ((t (:foreground ,teal-bright :weight bold :height 1.3))))
   `(shr-h2 ((t (:foreground ,green-bright :weight bold :height 1.2))))
   `(shr-h3 ((t (:foreground ,teal :weight semi-bold :height 1.1))))
   `(shr-h4 ((t (:foreground ,green :weight semi-bold))))
   `(shr-h5 ((t (:foreground ,teal-dim :weight semi-bold))))
   `(shr-h6 ((t (:foreground ,green-dim))))
   `(shr-link ((t (:foreground ,teal-bright :underline t))))
   `(shr-selected-link ((t (:foreground ,bg0 :background ,teal-bright :weight bold))))
   `(eww-valid-certificate ((t (:foreground ,green :weight semi-bold))))
   `(eww-invalid-certificate ((t (:foreground ,red :weight bold))))
   `(eww-form-url ((t (:foreground ,fg-1 :background ,bg1 :box (:line-width 1 :color ,bg3)))))
   `(eww-form-text ((t (:foreground ,fg0 :background ,bg2 :box (:line-width 1 :color ,bg3)))))
   `(eww-form-textarea ((t (:foreground ,fg0 :background ,bg2 :box (:line-width 1 :color ,bg3)))))
   `(eww-form-select ((t (:foreground ,fg0 :background ,bg2 :box (:line-width 1 :color ,bg3)))))
   `(eww-form-submit ((t (:foreground ,bg0 :background ,teal-bright :weight semi-bold :box (:line-width 1 :color ,bg4)))))
   `(eww-form-file ((t (:foreground ,bg0 :background ,teal :weight semi-bold :box (:line-width 1 :color ,bg4)))))
   `(eww-form-checkbox ((t (:foreground ,green-bright :background ,bg2 :box (:line-width 1 :color ,bg3)))))
   `(shr-code ((t (:foreground ,teal :background ,bg1 :box (:line-width 1 :color ,bg2)))))
   `(shr-abbreviation ((t (:underline (:color ,gray)))))
   `(shr-strike-through ((t (:strike-through t :foreground ,gray))))
   `(eww-history-url ((t (:foreground ,teal-bright :underline t))))
   `(eww-history-title ((t (:foreground ,fg0 :weight semi-bold))))
   `(markdown-header-face ((t (:inherit default :weight bold))))
   `(markdown-header-face-1 ((t (:inherit default :foreground ,teal-bright :weight bold :height 1.3))))
   `(markdown-header-face-2 ((t (:inherit default :foreground ,green-bright :weight bold :height 1.2))))
   `(markdown-header-face-3 ((t (:inherit default :foreground ,teal :weight semi-bold :height 1.1))))
   `(markdown-header-face-4 ((t (:inherit default :foreground ,green :weight semi-bold))))
   `(markdown-header-face-5 ((t (:inherit default :foreground ,teal-dim :weight semi-bold))))
   `(markdown-header-face-6 ((t (:inherit default :foreground ,green-dim :weight semi-bold))))
   `(markdown-header-delimiter-face ((t (:foreground ,bg4 :weight bold))))
   `(markdown-bold-face ((t (:foreground ,fg-1 :weight bold))))
   `(markdown-italic-face ((t (:foreground ,fg-1 :slant italic))))
   `(markdown-strike-through-face ((t (:foreground ,gray :strike-through t))))
   `(markdown-inline-code-face ((t (:foreground ,teal :background ,bg1 :inherit fixed-pitch :height 1.0))))
   `(markdown-code-face ((t (:background ,bg1 :extend t :inherit fixed-pitch :height 1.0))))
   `(markdown-pre-face ((t (:foreground ,fg-1 :background ,bg1 :inherit fixed-pitch :height 1.0))))
   `(markdown-language-keyword-face ((t (:foreground ,bg4 :slant italic :inherit fixed-pitch :height 1.0))))
   `(markdown-link-face ((t (:foreground ,teal-bright :underline t))))
   `(markdown-url-face ((t (:foreground ,teal-bright :underline t))))
   `(markdown-link-title-face ((t (:foreground ,green))))
   `(markdown-reference-face ((t (:foreground ,teal))))
   `(markdown-missing-link-face ((t (:foreground ,red :underline t :weight bold))))
   `(markdown-plain-url-face ((t (:foreground ,teal-bright :underline t :slant italic))))
   `(markdown-angle-bracket-face ((t (:foreground ,teal))))
   `(markdown-list-face ((t (:foreground ,green-bright :weight semi-bold))))
   `(markdown-blockquote-face ((t (:foreground ,gray :slant italic))))
   `(markdown-hr-face ((t (:foreground ,bg3 :weight bold))))
   `(markdown-yaml-key-face ((t (:foreground ,teal :weight semi-bold))))
   `(markdown-yaml-value-face ((t (:foreground ,green))))
   `(markdown-metadata-key-face ((t (:foreground ,teal :weight semi-bold))))
   `(markdown-metadata-value-face ((t (:foreground ,green))))
   `(markdown-html-tag-name-face ((t (:foreground ,teal-bright))))
   `(markdown-html-tag-delimiter-face ((t (:foreground ,fg3))))
   `(markdown-html-attr-name-face ((t (:foreground ,green-bright))))
   `(markdown-html-attr-value-face ((t (:foreground ,green))))
   `(markdown-html-entity-face ((t (:foreground ,teal))))
   `(markdown-gfm-checkbox-face ((t (:foreground ,green-bright :weight bold :inherit fixed-pitch :height 1.0))))
   `(markdown-footnote-marker-face ((t (:foreground ,teal-bright :weight semi-bold))))
   `(markdown-footnote-text-face ((t (:foreground ,fg3 :slant italic))))
   `(markdown-table-face ((t (:foreground ,fg3 :inherit fixed-pitch :height 1.0))))
   `(eldoc-highlight-function-argument ((t (:foreground ,green-bright :weight bold))))
   `(eldoc-box-body ((t (:background ,bg1 :foreground ,fg0))))
   `(eldoc-box-border ((t (:background ,bg3))))
   `(eldoc-box-scrollable-indicator ((t (:foreground ,gray))))
   `(web-mode-html-tag-face ((t (:foreground ,teal :weight normal))))
   `(web-mode-html-tag-bracket-face ((t (:foreground ,gray))))
   `(web-mode-html-tag-namespaced-face ((t (:foreground ,green-bright))))
   `(web-mode-html-attr-name-face ((t (:foreground ,green-bright))))
   `(web-mode-html-attr-equal-face ((t (:foreground ,fg0))))
   `(web-mode-html-attr-value-face ((t (:foreground ,green :slant italic))))
   `(web-mode-html-attr-custom-face ((t (:foreground ,teal-dim))))
   `(web-mode-html-attr-engine-face ((t (:foreground ,teal))))
   `(web-mode-html-entity-face ((t (:foreground ,teal))))
   `(web-mode-doctype-face ((t (:foreground ,gray :slant italic))))
   `(web-mode-comment-face ((t (:foreground ,gray :slant italic))))
   `(web-mode-server-comment-face ((t (:foreground ,bg4 :slant italic))))
   `(web-mode-css-selector-face ((t (:foreground ,green-bright :weight semi-bold))))
   `(web-mode-css-selector-class-face ((t (:foreground ,green-bright))))
   `(web-mode-css-selector-tag-face ((t (:foreground ,teal-bright))))
   `(web-mode-css-pseudo-class-face ((t (:foreground ,teal-dim))))
   `(web-mode-css-at-rule-face ((t (:foreground ,teal :weight semi-bold))))
   `(web-mode-css-property-name-face ((t (:foreground ,teal-bright))))
   `(web-mode-css-color-face ((t (:foreground ,teal-dim))))
   `(web-mode-css-priority-face ((t (:foreground ,red :weight bold))))
   `(web-mode-css-function-face ((t (:foreground ,green))))
   `(web-mode-css-variable-face ((t (:foreground ,teal :slant italic))))
   `(web-mode-css-comment-face ((t (:foreground ,gray :slant italic))))
   `(web-mode-css-string-face ((t (:foreground ,green :slant italic))))
   `(web-mode-json-key-face ((t (:foreground ,teal-bright))))
   `(web-mode-json-context-face ((t (:foreground ,gray))))
   `(web-mode-javascript-string-face ((t (:foreground ,green :slant italic))))
   `(web-mode-javascript-comment-face ((t (:foreground ,gray :slant italic))))
   `(web-mode-function-call-face ((t (:foreground ,fg0))))
   `(web-mode-block-face ((t (:background ,bg0-soft :extend t))))
   `(web-mode-block-delimiter-face ((t (:foreground ,teal-bright :weight bold))))
   `(web-mode-block-control-face ((t (:foreground ,teal-bright :weight semi-bold))))
   `(web-mode-block-comment-face ((t (:foreground ,gray :slant italic))))
   `(web-mode-block-string-face ((t (:foreground ,green :slant italic))))
   `(web-mode-part-face ((t (:background ,bg0))))
   `(web-mode-current-element-highlight-face ((t (:background ,bg2 :weight semi-bold))))
   `(web-mode-current-column-highlight-face ((t (:background ,bg1))))
   `(web-mode-whitespace-face ((t (:background ,bg-red))))
   `(web-mode-error-face ((t (:foreground ,red :underline (:style wave :color ,red)))))
   `(web-mode-warning-face ((t (:foreground ,teal-bright :underline (:style wave :color ,teal-bright)))))
   `(web-mode-folded-face ((t (:underline t))))
   `(anzu-mode-line                    ((t (:foreground ,green-bright :weight bold))))
   `(anzu-mode-line-no-match           ((t (:foreground ,red :weight bold))))
   `(anzu-match-1                      ((t (:background ,bg-green :foreground ,green))))
   `(anzu-match-2                      ((t (:background ,bg-teal :foreground ,teal-bright))))
   `(anzu-match-3                      ((t (:background ,bg2 :foreground ,teal-dim))))
   `(anzu-replace-to                   ((t (:foreground ,teal-bright :weight bold))))
   `(anzu-replace-highlight            ((t (:background ,bg-red :foreground ,red :weight bold))))
   `(org-superstar-header-bullet ((t (:height 1.2))))))

(provide-theme 'verdigris)

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-directory load-file-name)))

(provide 'verdigris)
;;; verdigris-theme.el ends here
