tab_title_template "{title}"
enable_audio_bell no

# --- Fonts ---
# font_family JetBrainsMono Nerd Font
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
# font_size        11.5


# --- Font Fallback for Arabic ---
font_family               JetBrainsMono Nerd Font
font_features             JetBrainsMonoNF-Regular +liga +calt
symbol_map                U+0600-U+06FF Noto Sans Arabic
symbol_map                U+0750-U+077F Noto Sans Arabic
symbol_map                U+08A0-U+08FF Noto Sans Arabic
symbol_map                U+FB50-U+FDFF Noto Sans Arabic
symbol_map                U+FE70-U+FEFF Noto Sans Arabic
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.5

text_composition_strategy legacy

# --- Ligatures ---
disable_ligatures never

# --- Cursor ---
cursor            #c8c093
cursor_shape      beam
cursor_blink_interval 0.5

# --- Window Layout ---
window_padding_width 2
confirm_os_window_close 0
# hide_window_decorations yes

# --- Transparency ---
background_opacity 0.90

# --- Scrolling ---
scrollback_lines 5000

# --- Performance ---
repaint_delay    10
input_delay      3
sync_to_monitor  yes

# Cursor
cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.05
cursor_shape block
cursor_blink true

# --- Tab Bar (Kanagawa-Dragon Style) ---
tab_bar_style           powerline
active_tab_background   #2d4f67
active_tab_foreground   #dcd7ba
inactive_tab_background #181616
inactive_tab_foreground #727169

# --- Color Scheme (Kanagawa-Dragon) ---
background           #181616
foreground           #c5c9c5
selection_background #2d4f67
selection_foreground #c5c9c5
url_color            #72a7c8

# Maps
# map ctrl+h discard_event
# map ctrl+j discard_event
# map ctrl+k discard_event
# map ctrl+l discard_event
#

# --- Terminal 16 Colors ---

# Black
color0 #0d0c0c
color8 #a6a69c

# Red
color1 #c4746e
color9 #e46876

# Green
color2  #8a9a7b
color10 #87a987

# Yellow
color3  #c4b28a
color11 #e6c384

# Blue
color4  #8ba4b0
color12 #7fb4ca

# Magenta
color5  #a292a3
color13 #938aa9

# Cyan
color6  #8ea4a2
color14 #7aa89f

# White
color7  #c8c093
color15 #c5c9c5
