#!/usr/bin/env sh
# i3blocks persistent blocklet for keyboard layout display
# Requires: xkb-switch

font=${font:-monospace}
font_weight=${font_weight:-bold}

while :
do
    # Output current layout
    xkb-switch -p | awk -v font="$font" -v font_weight="$font_weight" '
    {
        layout = toupper($0)

        sub(/\(.*/, "", layout)

        if (layout == "ARA")
            layout = "AR"

        print "<span font_family=\"" font "\" font_weight=\"" font_weight "\">" layout "</span>"
    }' || sleep 1

    # Wait for layout change
    xkb-switch -w
done
